### ISSUE TITLE
Fix 'Redefining built-in &#39;type&#39;' issue in crypto-telegram.py

### ISSUE THREAD

**Issue by arsovskidev** [arshetamine/Crypto-Telegram#3]
Found an issue: Redefining built-in &#39;type&#39;

It's currently on crypto-telegram/source/master/crypto-telegram.py#L51
Commit 6c2da7756ba00a6277b29c7bf9a3a1abc524c1f2

**Comment by arshetamine** [comment]
Commit 3227a7794e487d96478692ba01c9f07ed9c3c411
